### ISSUE TITLE
Calendar does not start at week 0

### ISSUE THREAD

**Issue by kshannon** [kshannon-ucsd/cogs8#3]
@vchelur97 I forget, did we (by that I mean you lol) already fix this in Cogs 9 repo? Also finals week is showing up as week 12 (not 11) because of this starting at 1 not 0 bug I suppose?  class website [link](https://kshannon.github.io/ucsd-cogs8/)

<img width="783" alt="image" src="https://github.com/kshannon/ucsd-cogs8/assets/1323888/7cc50fe5-48d6-4ccb-961c-a471fe0ed91d">

<img width="978" alt="image" src="https://github.com/kshannon/ucsd-cogs8/assets/1323888/6d38fc80-b246-4b4e-b69d-6a8615115e8b">

**Comment by crvineeth97** [comment]
It's a bug... I'm pretty sure I had fixed it but it crawled back in. I'll take a look at it over the weekend

**Comment by vchelur97** [comment]
Fixed
